package similar

var DescriptionLanguages = []string{
	"Spanish:[spoiler]",
	"Russian:[spoiler]",
	"French:[spoiler]",
	"Spanish[spoiler]",
	"Russian[spoiler]",
	"French[spoiler]",
	"Chinese[spoiler]",
	"Spanish [spoiler]",
	"Russian [spoiler]",
	"French [spoiler]",
	"Chinese [spoiler]",
	"French\n[spoiler]",
	"Russian\n[spoiler]",
	"Spanish\n[spoiler]",
	"Chinese\n[spoiler]",
	"French:",
	"Russian:",
	"Spanish:",
	"Chinese:",
	"\n\nFrench",
	"\n\nRussian",
	"\n\nSpanish",
	"\n\nChinese",
	"\n\nfrench",
	"\n\nrussian",
	"\n\nspanish",
	"\n\nchinese",
	"Russian / Русский",
	"[u]Russian",
	"[b][u]Russian",
	"[RUS]",
	"Russian / Русский",
	"Russian/Русский:",
	"Russia/Русское",
	"[hr]Russian/русский:",
	"Русский",
	"RUS:",
	"[b][u]German / Deutsch",
	"German/Deutsch:",
	"Espa&ntilde;ol / Spanish",
	"Spanish / Espa&ntilde;ol",
	"Spanish / Espa & ntilde; ol",
	"Spanish / Espa&ntilde;ol",
	"[b][u]Spanish",
	"[Espa&ntilde;ol]:",
	"[b] Spanish: [/ b]",
	"정보",
	"Spanish/Espa&ntilde;ol",
	"Espa&ntilde;ol / Spanish",
	"Italian / Italiano",
	"Italian/Italiano",
	"\r\n\r\nItalian\r\n",
	"Pasta-Pizza-Mandolino/Italiano",
	"Persian /فارسی",
	"Farsi/Persian/",
	"Polish / polski",
	"Polish / Polski",
	"Polish Summary / Polski Opis",
	"Polski",
	"Portuguese (BR) / Portugu&ecirc;s",
	"Portuguese / Portugu&ecirc;s",
	"Português / Portuguese",
	"Portuguese / Portugu",
	"Portuguese / Portugu&ecirc;s",
	"Portugu&ecirc;s",
	"Portuguese (BR) / Portugu & ecirc;",
	"Portuguese (BR) / Portugu&ecirc;",
	"[PTBR]",
	"R&eacute;sume Fran&ccedil;ais",
	"R&eacute;sum&eacute; Fran&ccedil;ais",
	"[b][u]French",
	"French / Fran&ccedil;ais",
	"Fran&ccedil;ais",
	"[hr]Fr:",
	"French - Français:",
	"Turkish / T&uuml;rk&ccedil;e",
	"Turkish/T&uuml;rk&ccedil;e",
	"T&uuml;rk&ccedil;e",
	"[b][u]Chinese",
	"Arabic / العربية",
	"العربية",
	"[hr]TH",
	"[b][u]Vietnamese",
	"[b]Links:",
	"[b]Link[/b]",
	"Links:",
	"[b]External Links",
	"[hr][b][u]Descriptions in Other Languages:[/u][/b]",
}

var EnglishDescriptionTags = []string{
	"[b][u]English:",
	"[b][u]English",
	"[English]:",
	"[B][ENG][/B]",
	"English:",
	"Official English",
	"official english",
}

var BBCodes = []string{
	"[list]",
	"[/list]",
	"[*]",
	"[hr]",
	"[u]",
	"[/u]",
	"[b]",
	"[/b]",
}

var StopWords = []string{"a", "about", "above", "above", "across", "after", "afterwards", "again", "against",
	"all", "almost", "alone", "along", "already", "also", "although", "always", "am", "among", "amongst",
	"amoungst", "amount", "an", "and", "another", "any", "anyhow", "anyone", "anything", "anyway", "anywhere",
	"are", "around", "as", "at", "back", "be", "became", "because", "become", "becomes", "becoming", "been",
	"before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both",
	"bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de",
	"describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven",
	"else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything",
	"everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former",
	"formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has",
	"hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself",
	"him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into",
	"is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many",
	"may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much",
	"must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody",
	"none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only",
	"onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own", "part", "per",
	"perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious",
	"several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow",
	"someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten",
	"than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby",
	"therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though",
	"three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards",
	"twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well",
	"were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby",
	"wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole",
	"whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours",
	"yourself", "yourselves"}
