/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * API version: 5.9.0
 * Contact: support@mangadex.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mangadex

type InlineResponse20013RatingDistribution struct {
	Var1 int32 `json:"1,omitempty"`
	Var2 int32 `json:"2,omitempty"`
	Var3 int32 `json:"3,omitempty"`
	Var4 int32 `json:"4,omitempty"`
	Var5 int32 `json:"5,omitempty"`
	Var6 int32 `json:"6,omitempty"`
	Var7 int32 `json:"7,omitempty"`
	Var8 int32 `json:"8,omitempty"`
	Var9 int32 `json:"9,omitempty"`
	Var10 int32 `json:"10,omitempty"`
}
