/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * API version: 5.9.0
 * Contact: support@mangadex.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mangadex

type Chapter struct {
	Id         string `json:"id"`
	Type       string `json:"type"`
	Attributes struct {
		Title              string `json:"title"`
		Volume             string `json:"volume"`
		Chapter            string `json:"chapter"`
		Pages              int    `json:"pages"`
		TranslatedLanguage string `json:"translatedLanguage"`
		Uploader           string `json:"uploader"`
		ExternalUrl        string `json:"externalUrl"`
		Version            int    `json:"version"`
		CreatedAt          string `json:"createdAt"`
		UpdatedAt          string `json:"updatedAt"`
		PublishAt          string `json:"publishAt"`
		ReadableAt         string `json:"readableAt"`
	} `json:"attributes"`
	Relationships []Relationship `json:"relationships"`
}
